In [1]:
import numpy as np
import pandas as pd
import requests

In [2]:
#Importing countries through api
url="https://api.worldbank.org/countries?format=json&per_page=300"
response=requests.get(url)
response.status_code

200

In [3]:
data=response.json()
print(data[0])

{'page': 1, 'pages': 1, 'per_page': '300', 'total': 295}

In [4]:
countries=data[1]
countries=pd.DataFrame(countries)

In [5]:
countries

,id,iso2Code,name,region,adminregion,incomeLevel,lendingType,capitalCity,longitude,latitude
0,ABW,AW,Aruba,"{'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Lati...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...","{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",Oranjestad,-70.0167,12.5167
1,AFE,ZH,Africa Eastern and Southern,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
2,AFG,AF,Afghanistan,"{'id': 'MEA', 'iso2code': 'ZQ', 'value': 'Midd...","{'id': 'MNA', 'iso2code': 'XQ', 'value': 'Midd...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Kabul,69.1761,34.5228
3,AFR,A9,Africa,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
4,AFW,ZI,Africa Western and Central,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
...,...,...,...,...,...,...,...,...,...,...
290,XZN,A5,Sub-Saharan Africa excluding South Africa and ...,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
291,YEM,YE,"Yemen, Rep.","{'id': 'MEA', 'iso2code': 'ZQ', 'value': 'Midd...","{'id': 'MNA', 'iso2code': 'XQ', 'value': 'Midd...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Sana'a,44.2075,15.352
292,ZAF,ZA,South Africa,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'UMC', 'iso2code': 'XT', 'value': 'Uppe...","{'id': 'IBD', 'iso2code': 'XF', 'value': 'IBRD'}",Pretoria,28.1871,-25.746
293,ZMB,ZM,Zambia,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Lusaka,28.2937,-15.3982
294,ZWE,ZW,Zimbabwe,"{'id': 'SSF', 'iso2code': 'ZG', 'value': 'Sub-...","{'id': 'SSA', 'iso2code': 'ZF', 'value': 'Sub-...","{'id': 'LMC', 'iso2code': 'XN', 'value': 'Lowe...","{'id': 'IDB', 'iso2code': 'XH', 'value': 'Blend'}",Harare,31.0672,-17.8312

In [6]:
countries['region']=countries['region'].apply(lambda x:x['value'])
countries['incomeLevel']= countries['incomeLevel'].apply(lambda x:x['value'])
countries['lendingType']= countries['lendingType'].apply(lambda x:x['value'])

In [7]:
countries.rename(columns={'iso2Code':'country_id'},inplace=True)
countries.drop(columns=['adminregion','lendingType','capitalCity'],inplace=True)

In [8]:
countries

,id,country_id,name,region,incomeLevel,longitude,latitude
0,ABW,AW,Aruba,Latin America & Caribbean,High income,-70.0167,12.5167
1,AFE,ZH,Africa Eastern and Southern,Aggregates,Aggregates,,
2,AFG,AF,Afghanistan,"Middle East, North Africa, Afghanistan & Pakistan",Low income,69.1761,34.5228
3,AFR,A9,Africa,Aggregates,Aggregates,,
4,AFW,ZI,Africa Western and Central,Aggregates,Aggregates,,
...,...,...,...,...,...,...,...
290,XZN,A5,Sub-Saharan Africa excluding South Africa and ...,Aggregates,Aggregates,,
291,YEM,YE,"Yemen, Rep.","Middle East, North Africa, Afghanistan & Pakistan",Low income,44.2075,15.352
292,ZAF,ZA,South Africa,Sub-Saharan Africa,Upper middle income,28.1871,-25.746
293,ZMB,ZM,Zambia,Sub-Saharan Africa,Lower middle income,28.2937,-15.3982
294,ZWE,ZW,Zimbabwe,Sub-Saharan Africa,Lower middle income,31.0672,-17.8312

In [9]:
#code for indicators
ind_url='https://api.worldbank.org/v2/indicators?format=json'
response=requests.get(ind_url)
response.status_code

200

In [10]:
indicators_data=response.json()
indicators_data[0]

{'page': 1, 'pages': 591, 'per_page': '50', 'total': 29544}

In [11]:
all_dfs = []

for i in range(1, 592):
    url = f"https://api.worldbank.org/v2/indicators?format=json&per_page=500&page={i}"

    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()

        if len(data) < 2 or not data[1]:
            print(f"No data at page {i}")

        df = pd.DataFrame([
            {"id": item["id"], "name": item["name"]}
            for item in data[1]
        ])

        all_dfs.append(df)
        print(f"Page {i}: {len(df)} indicators collected")

    else:
        print(f"Failed to fetch page {i}, status code {response.status_code}")

Page 1: 500 indicators collected
Page 2: 500 indicators collected
Page 3: 500 indicators collected
Page 4: 500 indicators collected
Page 5: 500 indicators collected
Page 6: 500 indicators collected
Page 7: 500 indicators collected
Page 8: 500 indicators collected
Page 9: 500 indicators collected
Page 10: 500 indicators collected
Page 11: 500 indicators collected
Page 12: 500 indicators collected
Page 13: 500 indicators collected
Page 14: 500 indicators collected
Page 15: 500 indicators collected
Page 16: 500 indicators collected
Page 17: 500 indicators collected
Page 18: 500 indicators collected
Page 19: 500 indicators collected
Page 20: 500 indicators collected
Page 21: 500 indicators collected
Page 22: 500 indicators collected
Page 23: 500 indicators collected
Page 24: 500 indicators collected
Page 25: 500 indicators collected
Page 26: 500 indicators collected
Page 27: 500 indicators collected
Page 28: 500 indicators collected
Page 29: 500 indicators collected
Page 30: 500 indicators collected
Page 31: 500 indicators collected
Page 32: 500 indicators collected
Page 33: 500 indicators collected
Page 34: 500 indicators collected
Page 35: 500 indicators collected
Page 36: 500 indicators collected
Page 37: 500 indicators collected
Page 38: 500 indicators collected
Page 39: 500 indicators collected
Page 40: 500 indicators collected
Page 41: 500 indicators collected
Page 42: 500 indicators collected
Page 43: 500 indicators collected
Page 44: 500 indicators collected
Page 45: 500 indicators collected
Page 46: 500 indicators collected
Page 47: 500 indicators collected
Page 48: 500 indicators collected
Page 49: 500 indicators collected
Page 50: 500 indicators collected
Page 51: 500 indicators collected
Page 52: 500 indicators collected
Page 53: 500 indicators collected
Page 54: 500 indicators collected
Page 55: 500 indicators collected
Page 56: 500 indicators collected
Page 57: 500 indicators collected
Page 58: 500 indicators collected
Page 59: 500 indicators collected
Page 60: 44 indicators collected
No data at page 61
Page 61: 0 indicators collected
No data at page 62
Page 62: 0 indicators collected
No data at page 63
Page 63: 0 indicators collected
No data at page 64
Page 64: 0 indicators collected
No data at page 65
Page 65: 0 indicators collected
No data at page 66
Page 66: 0 indicators collected
No data at page 67
Page 67: 0 indicators collected
No data at page 68
Page 68: 0 indicators collected
No data at page 69
Page 69: 0 indicators collected
No data at page 70
Page 70: 0 indicators collected
No data at page 71
Page 71: 0 indicators collected
No data at page 72
Page 72: 0 indicators collected
No data at page 73
Page 73: 0 indicators collected
No data at page 74
Page 74: 0 indicators collected
No data at page 75
Page 75: 0 indicators collected
No data at page 76
Page 76: 0 indicators collected
No data at page 77
Page 77: 0 indicators collected
No data at page 78
Page 78: 0 indicators collected
No data at page 79
Page 79: 0 indicators collected
No data at page 80
Page 80: 0 indicators collected
No data at page 81
Page 81: 0 indicators collected
No data at page 82
Page 82: 0 indicators collected
No data at page 83
Page 83: 0 indicators collected
No data at page 84
Page 84: 0 indicators collected
No data at page 85
Page 85: 0 indicators collected
No data at page 86
Page 86: 0 indicators collected
No data at page 87
Page 87: 0 indicators collected
No data at page 88
Page 88: 0 indicators collected
No data at page 89
Page 89: 0 indicators collected
No data at page 90
Page 90: 0 indicators collected
No data at page 91
Page 91: 0 indicators collected
No data at page 92
Page 92: 0 indicators collected
No data at page 93
Page 93: 0 indicators collected
No data at page 94
Page 94: 0 indicators collected
No data at page 95
Page 95: 0 indicators collected
No data at page 96
Page 96: 0 indicators collected
No data at page 97
Page 97: 0 indicators collected
No data at page 98
Page 98: 0 indicators collected
No data at page 99
Page 99: 0 indicators collected
No data at page 100
Page 100: 0 indicators collected
No data at page 101
Page 101: 0 indicators collected
No data at page 102
Page 102: 0 indicators collected
No data at page 103
Page 103: 0 indicators collected
No data at page 104
Page 104: 0 indicators collected
No data at page 105
Page 105: 0 indicators collected
No data at page 106
Page 106: 0 indicators collected
No data at page 107
Page 107: 0 indicators collected
No data at page 108
Page 108: 0 indicators collected
No data at page 109
Page 109: 0 indicators collected
No data at page 110
Page 110: 0 indicators collected
No data at page 111
Page 111: 0 indicators collected
No data at page 112
Page 112: 0 indicators collected
No data at page 113
Page 113: 0 indicators collected
No data at page 114
Page 114: 0 indicators collected
No data at page 115
Page 115: 0 indicators collected
No data at page 116
Page 116: 0 indicators collected
No data at page 117
Page 117: 0 indicators collected
No data at page 118
Page 118: 0 indicators collected
No data at page 119
Page 119: 0 indicators collected
No data at page 120
Page 120: 0 indicators collected
No data at page 121
Page 121: 0 indicators collected
No data at page 122
Page 122: 0 indicators collected
No data at page 123
Page 123: 0 indicators collected
No data at page 124
Page 124: 0 indicators collected
No data at page 125
Page 125: 0 indicators collected
No data at page 126
Page 126: 0 indicators collected
No data at page 127
Page 127: 0 indicators collected
No data at page 128
Page 128: 0 indicators collected
No data at page 129
Page 129: 0 indicators collected
No data at page 130
Page 130: 0 indicators collected
No data at page 131
Page 131: 0 indicators collected
No data at page 132
Page 132: 0 indicators collected
No data at page 133
Page 133: 0 indicators collected
No data at page 134
Page 134: 0 indicators collected
No data at page 135
Page 135: 0 indicators collected
No data at page 136
Page 136: 0 indicators collected
No data at page 137
Page 137: 0 indicators collected
No data at page 138
Page 138: 0 indicators collected
No data at page 139
Page 139: 0 indicators collected
No data at page 140
Page 140: 0 indicators collected
No data at page 141
Page 141: 0 indicators collected
No data at page 142
Page 142: 0 indicators collected
No data at page 143
Page 143: 0 indicators collected
No data at page 144
Page 144: 0 indicators collected
No data at page 145
Page 145: 0 indicators collected
No data at page 146
Page 146: 0 indicators collected
No data at page 147
Page 147: 0 indicators collected
No data at page 148
Page 148: 0 indicators collected
No data at page 149
Page 149: 0 indicators collected
No data at page 150
Page 150: 0 indicators collected
No data at page 151
Page 151: 0 indicators collected
No data at page 152
Page 152: 0 indicators collected
No data at page 153
Page 153: 0 indicators collected
No data at page 154
Page 154: 0 indicators collected
No data at page 155
Page 155: 0 indicators collected
No data at page 156
Page 156: 0 indicators collected
No data at page 157
Page 157: 0 indicators collected
No data at page 158
Page 158: 0 indicators collected
No data at page 159
Page 159: 0 indicators collected
No data at page 160
Page 160: 0 indicators collected
No data at page 161
Page 161: 0 indicators collected
No data at page 162
Page 162: 0 indicators collected
No data at page 163
Page 163: 0 indicators collected
No data at page 164
Page 164: 0 indicators collected
No data at page 165
Page 165: 0 indicators collected
No data at page 166
Page 166: 0 indicators collected
No data at page 167
Page 167: 0 indicators collected
No data at page 168
Page 168: 0 indicators collected
No data at page 169
Page 169: 0 indicators collected
No data at page 170
Page 170: 0 indicators collected
No data at page 171
Page 171: 0 indicators collected
No data at page 172
Page 172: 0 indicators collected
No data at page 173
Page 173: 0 indicators collected
No data at page 174
Page 174: 0 indicators collected
No data at page 175
Page 175: 0 indicators collected
No data at page 176
Page 176: 0 indicators collected
No data at page 177
Page 177: 0 indicators collected
No data at page 178
Page 178: 0 indicators collected
No data at page 179
Page 179: 0 indicators collected
No data at page 180
Page 180: 0 indicators collected
No data at page 181
Page 181: 0 indicators collected
No data at page 182
Page 182: 0 indicators collected
No data at page 183
Page 183: 0 indicators collected
No data at page 184
Page 184: 0 indicators collected
No data at page 185
Page 185: 0 indicators collected
No data at page 186
Page 186: 0 indicators collected
No data at page 187
Page 187: 0 indicators collected
No data at page 188
Page 188: 0 indicators collected
No data at page 189
Page 189: 0 indicators collected
No data at page 190
Page 190: 0 indicators collected
No data at page 191
Page 191: 0 indicators collected
No data at page 192
Page 192: 0 indicators collected
No data at page 193
Page 193: 0 indicators collected
No data at page 194
Page 194: 0 indicators collected
No data at page 195
Page 195: 0 indicators collected
No data at page 196
Page 196: 0 indicators collected
No data at page 197
Page 197: 0 indicators collected
No data at page 198
Page 198: 0 indicators collected
No data at page 199
Page 199: 0 indicators collected
No data at page 200
Page 200: 0 indicators collected
No data at page 201
Page 201: 0 indicators collected
No data at page 202
Page 202: 0 indicators collected
No data at page 203
Page 203: 0 indicators collected
No data at page 204
Page 204: 0 indicators collected
No data at page 205
Page 205: 0 indicators collected
No data at page 206
Page 206: 0 indicators collected
No data at page 207
Page 207: 0 indicators collected
No data at page 208
Page 208: 0 indicators collected
No data at page 209
Page 209: 0 indicators collected
No data at page 210
Page 210: 0 indicators collected
No data at page 211
Page 211: 0 indicators collected
No data at page 212
Page 212: 0 indicators collected
No data at page 213
Page 213: 0 indicators collected
No data at page 214
Page 214: 0 indicators collected
No data at page 215
Page 215: 0 indicators collected
No data at page 216
Page 216: 0 indicators collected
No data at page 217
Page 217: 0 indicators collected
No data at page 218
Page 218: 0 indicators collected
No data at page 219
Page 219: 0 indicators collected
No data at page 220
Page 220: 0 indicators collected
No data at page 221
Page 221: 0 indicators collected
No data at page 222
Page 222: 0 indicators collected
No data at page 223
Page 223: 0 indicators collected
No data at page 224
Page 224: 0 indicators collected
No data at page 225
Page 225: 0 indicators collected
No data at page 226
Page 226: 0 indicators collected
No data at page 227
Page 227: 0 indicators collected
No data at page 228
Page 228: 0 indicators collected
No data at page 229
Page 229: 0 indicators collected
No data at page 230
Page 230: 0 indicators collected
No data at page 231
Page 231: 0 indicators collected
No data at page 232
Page 232: 0 indicators collected
No data at page 233
Page 233: 0 indicators collected
No data at page 234
Page 234: 0 indicators collected
No data at page 235
Page 235: 0 indicators collected
No data at page 236
Page 236: 0 indicators collected
No data at page 237
Page 237: 0 indicators collected
No data at page 238
Page 238: 0 indicators collected
No data at page 239
Page 239: 0 indicators collected
No data at page 240
Page 240: 0 indicators collected
No data at page 241
Page 241: 0 indicators collected
No data at page 242
Page 242: 0 indicators collected
No data at page 243
Page 243: 0 indicators collected
No data at page 244
Page 244: 0 indicators collected
No data at page 245
Page 245: 0 indicators collected
No data at page 246
Page 246: 0 indicators collected
No data at page 247
Page 247: 0 indicators collected
No data at page 248
Page 248: 0 indicators collected
No data at page 249
Page 249: 0 indicators collected
No data at page 250
Page 250: 0 indicators collected
No data at page 251
Page 251: 0 indicators collected
No data at page 252
Page 252: 0 indicators collected
No data at page 253
Page 253: 0 indicators collected
No data at page 254
Page 254: 0 indicators collected
No data at page 255
Page 255: 0 indicators collected
No data at page 256
Page 256: 0 indicators collected
No data at page 257
Page 257: 0 indicators collected
No data at page 258
Page 258: 0 indicators collected
No data at page 259
Page 259: 0 indicators collected
No data at page 260
Page 260: 0 indicators collected
No data at page 261
Page 261: 0 indicators collected
No data at page 262
Page 262: 0 indicators collected
No data at page 263
Page 263: 0 indicators collected
No data at page 264
Page 264: 0 indicators collected
No data at page 265
Page 265: 0 indicators collected
No data at page 266
Page 266: 0 indicators collected
No data at page 267
Page 267: 0 indicators collected
No data at page 268
Page 268: 0 indicators collected
No data at page 269
Page 269: 0 indicators collected
No data at page 270
Page 270: 0 indicators collected
No data at page 271
Page 271: 0 indicators collected
No data at page 272
Page 272: 0 indicators collected
No data at page 273
Page 273: 0 indicators collected
No data at page 274
Page 274: 0 indicators collected
No data at page 275
Page 275: 0 indicators collected
No data at page 276
Page 276: 0 indicators collected
No data at page 277
Page 277: 0 indicators collected
No data at page 278
Page 278: 0 indicators collected
No data at page 279
Page 279: 0 indicators collected
No data at page 280
Page 280: 0 indicators collected
No data at page 281
Page 281: 0 indicators collected
No data at page 282
Page 282: 0 indicators collected
No data at page 283
Page 283: 0 indicators collected
No data at page 284
Page 284: 0 indicators collected
No data at page 285
Page 285: 0 indicators collected
No data at page 286
Page 286: 0 indicators collected
No data at page 287
Page 287: 0 indicators collected
No data at page 288
Page 288: 0 indicators collected
No data at page 289
Page 289: 0 indicators collected
No data at page 290
Page 290: 0 indicators collected
No data at page 291
Page 291: 0 indicators collected
No data at page 292
Page 292: 0 indicators collected
No data at page 293
Page 293: 0 indicators collected
No data at page 294
Page 294: 0 indicators collected
No data at page 295
Page 295: 0 indicators collected
No data at page 296
Page 296: 0 indicators collected
No data at page 297
Page 297: 0 indicators collected
No data at page 298
Page 298: 0 indicators collected
No data at page 299
Page 299: 0 indicators collected
No data at page 300
Page 300: 0 indicators collected
No data at page 301
Page 301: 0 indicators collected
No data at page 302
Page 302: 0 indicators collected
No data at page 303
Page 303: 0 indicators collected
No data at page 304
Page 304: 0 indicators collected
No data at page 305
Page 305: 0 indicators collected
No data at page 306
Page 306: 0 indicators collected
No data at page 307
Page 307: 0 indicators collected
No data at page 308
Page 308: 0 indicators collected
No data at page 309
Page 309: 0 indicators collected
No data at page 310
Page 310: 0 indicators collected
No data at page 311
Page 311: 0 indicators collected
No data at page 312
Page 312: 0 indicators collected
No data at page 313
Page 313: 0 indicators collected
No data at page 314
Page 314: 0 indicators collected
No data at page 315
Page 315: 0 indicators collected
No data at page 316
Page 316: 0 indicators collected
No data at page 317
Page 317: 0 indicators collected
No data at page 318
Page 318: 0 indicators collected
No data at page 319
Page 319: 0 indicators collected
No data at page 320
Page 320: 0 indicators collected
No data at page 321
Page 321: 0 indicators collected
No data at page 322
Page 322: 0 indicators collected
No data at page 323
Page 323: 0 indicators collected
No data at page 324
Page 324: 0 indicators collected
No data at page 325
Page 325: 0 indicators collected
No data at page 326
Page 326: 0 indicators collected
No data at page 327
Page 327: 0 indicators collected
No data at page 328
Page 328: 0 indicators collected
No data at page 329
Page 329: 0 indicators collected
No data at page 330
Page 330: 0 indicators collected
No data at page 331
Page 331: 0 indicators collected
No data at page 332
Page 332: 0 indicators collected
No data at page 333
Page 333: 0 indicators collected
No data at page 334
Page 334: 0 indicators collected
No data at page 335
Page 335: 0 indicators collected
No data at page 336
Page 336: 0 indicators collected
No data at page 337
Page 337: 0 indicators collected
No data at page 338
Page 338: 0 indicators collected
No data at page 339
Page 339: 0 indicators collected
No data at page 340
Page 340: 0 indicators collected
No data at page 341
Page 341: 0 indicators collected
No data at page 342
Page 342: 0 indicators collected
No data at page 343
Page 343: 0 indicators collected
No data at page 344
Page 344: 0 indicators collected
No data at page 345
Page 345: 0 indicators collected
No data at page 346
Page 346: 0 indicators collected
No data at page 347
Page 347: 0 indicators collected
No data at page 348
Page 348: 0 indicators collected
No data at page 349
Page 349: 0 indicators collected
No data at page 350
Page 350: 0 indicators collected
No data at page 351
Page 351: 0 indicators collected
No data at page 352
Page 352: 0 indicators collected
No data at page 353
Page 353: 0 indicators collected
No data at page 354
Page 354: 0 indicators collected
No data at page 355
Page 355: 0 indicators collected
No data at page 356
Page 356: 0 indicators collected
No data at page 357
Page 357: 0 indicators collected
No data at page 358
Page 358: 0 indicators collected
No data at page 359
Page 359: 0 indicators collected
No data at page 360
Page 360: 0 indicators collected
No data at page 361
Page 361: 0 indicators collected
No data at page 362
Page 362: 0 indicators collected
No data at page 363
Page 363: 0 indicators collected
No data at page 364
Page 364: 0 indicators collected
No data at page 365
Page 365: 0 indicators collected
No data at page 366
Page 366: 0 indicators collected
No data at page 367
Page 367: 0 indicators collected
No data at page 368
Page 368: 0 indicators collected
No data at page 369
Page 369: 0 indicators collected
No data at page 370
Page 370: 0 indicators collected
No data at page 371
Page 371: 0 indicators collected
No data at page 372
Page 372: 0 indicators collected
No data at page 373
Page 373: 0 indicators collected
No data at page 374
Page 374: 0 indicators collected
No data at page 375
Page 375: 0 indicators collected
No data at page 376
Page 376: 0 indicators collected
No data at page 377
Page 377: 0 indicators collected
No data at page 378
Page 378: 0 indicators collected
No data at page 379
Page 379: 0 indicators collected
No data at page 380
Page 380: 0 indicators collected
No data at page 381
Page 381: 0 indicators collected
No data at page 382
Page 382: 0 indicators collected
No data at page 383
Page 383: 0 indicators collected
No data at page 384
Page 384: 0 indicators collected
No data at page 385
Page 385: 0 indicators collected
No data at page 386
Page 386: 0 indicators collected
No data at page 387
Page 387: 0 indicators collected
No data at page 388
Page 388: 0 indicators collected
No data at page 389
Page 389: 0 indicators collected
No data at page 390
Page 390: 0 indicators collected
No data at page 391
Page 391: 0 indicators collected
No data at page 392
Page 392: 0 indicators collected
No data at page 393
Page 393: 0 indicators collected
No data at page 394
Page 394: 0 indicators collected
No data at page 395
Page 395: 0 indicators collected
No data at page 396
Page 396: 0 indicators collected
No data at page 397
Page 397: 0 indicators collected
No data at page 398
Page 398: 0 indicators collected
No data at page 399
Page 399: 0 indicators collected
No data at page 400
Page 400: 0 indicators collected
No data at page 401

In [12]:
final_df=pd.concat(all_dfs,ignore_index=True)
final_df.to_csv('final_df.csv')

In [13]:
# extract value for various indicators for each country
indicator_groups = {
"economic_activity_growth": [
"NY.GDP.MKTP.KD.ZG", # GDP growth (annual %)
"NY.GDP.PCAP.CD" # GDP per capita (current US$)
],
"labour_market_indicators": [
"SL.UEM.TOTL.ZS", # Unemployment total
"SL.UEM.1524.ZS", # Unemployment youth total (ages 15–24)
"SL.TLF.TOTL.IN" # Labour force, total
],
"trade_globalization": [
"NE.EXP.GNFS.CD", # Exports of goods and services (current US$)
"NE.IMP.GNFS.CD" # Imports of goods and services (current US$)
],
"poverty_inequality": [
"SI.POV.NAHC", # Poverty headcount ratio at national poverty lines (% of population)
"SI.POV.GINI" # Gini index (measure of income inequality)
],
"environmental_indicators": [
"EG.FEC.RNEW.ZS", # Renewable energy consumption (% of total final energy consumption)
"AG.LND.FRST.ZS" # Forest area (% of land area)
],
"health_indicators": [
"SP.DYN.LE00.IN", # Life expectancy at birth
"SP.DYN.IMRT.IN", # Infant mortality rate
"SH.H2O.BASW.ZS", # Access to at least basic water services (% of population)
"SH.XPD.CHEX.GD.ZS", # Current health expenditure (% of GDP)
"SH.IMM.IDPT", # Immunization, DPT (% of children ages 12–23 months)
"SH.IMM.MEAS", # Immunization, measles (% of children ages 12–23 months)
"SH.MMR.RISK.ZS", # Risk of maternal death
"SH.DTH.COMM.ZS", # Deaths from communicable diseases (% of total)
"SH.TBS.INCD", # Tuberculosis incidence (per 100,000 people)
"SH.STA.BRTC.ZS", # Births attended by skilled health staff (%)
"SH.STA.MMRT", # Maternal mortality ratio (modeled estimate, per 100,000 live births)
"SP.POP.65UP.TO.ZS", # Population ages 65 and above (% of total population)
"SH.HIV.INCD.ZS" # HIV incidence rate (per 1,000 uninfected population ages 15–49)
],
"technology_indicators": [
"IT.NET.USER.ZS", # Individuals using the Internet (% of population)
"IT.CEL.SETS.P2" # Mobile cellular subscriptions (per 100 people)
]}

In [14]:
for i,j in indicator_groups.items():
  print(j)

['NY.GDP.MKTP.KD.ZG', 'NY.GDP.PCAP.CD']
['SL.UEM.TOTL.ZS', 'SL.UEM.1524.ZS', 'SL.TLF.TOTL.IN']
['NE.EXP.GNFS.CD', 'NE.IMP.GNFS.CD']
['SI.POV.NAHC', 'SI.POV.GINI']
['EG.FEC.RNEW.ZS', 'AG.LND.FRST.ZS']
['SP.DYN.LE00.IN', 'SP.DYN.IMRT.IN', 'SH.H2O.BASW.ZS', 'SH.XPD.CHEX.GD.ZS', 'SH.IMM.IDPT', 'SH.IMM.MEAS', 'SH.MMR.RISK.ZS', 'SH.DTH.COMM.ZS', 'SH.TBS.INCD', 'SH.STA.BRTC.ZS', 'SH.STA.MMRT', 'SP.POP.65UP.TO.ZS', 'SH.HIV.INCD.ZS']
['IT.NET.USER.ZS', 'IT.CEL.SETS.P2']

In [15]:
import time

session = requests.Session()
base_url="https://api.worldbank.org/countries/all/indicators/{}?format=json&per_page=1000&page={}"
category_dataframes = {}

for category, indicators in indicator_groups.items():
    print(f"Fetching {category}")

    rows = []

    for indicator in indicators:
        page = 1

        while True:
            url = base_url.format(indicator, page)

            response = session.get(url)

            if response.status_code != 200:
                print(f"Failed: {indicator}")
                break

            data = response.json()

            if len(data) < 2 or not data[1]:
                break

            total_pages = data[0]["pages"]

            for r in data[1]:
                year = int(r["date"])

                if year > 2015:
                    rows.append({
                        "country_id": r["country"]["id"],
                        "country_name": r["country"]["value"],
                        "indicator_id": r["indicator"]["id"],
                        "indicator_name": r["indicator"]["value"],
                        "year": year,
                        "value": r["value"]
                    })

            if page >= total_pages:
                break

            page += 1
            time.sleep(0.2)

    category_dataframes[category] = pd.DataFrame(rows)

    print(f"{category}: {len(rows)} rows")

Fetching economic_activity_growth
economic_activity_growth: 5300 rows
Fetching labour_market_indicators
labour_market_indicators: 7950 rows
Fetching trade_globalization
trade_globalization: 5300 rows
Fetching poverty_inequality
poverty_inequality: 5300 rows
Fetching environmental_indicators
environmental_indicators: 5300 rows
Fetching health_indicators
health_indicators: 34450 rows
Fetching technology_indicators
technology_indicators: 5300 rows

In [16]:
economic_activity= category_dataframes.get("economic_activity_growth", pd.DataFrame())
labour_market_jobs= category_dataframes.get("labour_market_indicators", pd.DataFrame())
trade_globalization= category_dataframes.get("trade_globalization", pd.DataFrame())
poverty_inequality= category_dataframes.get("poverty_inequality", pd.DataFrame())
environmental_indicators= category_dataframes.get("environmental_indicators", pd.DataFrame())
health_indicators= category_dataframes.get("health_indicators", pd.DataFrame())
technology_indicators= category_dataframes.get("technology_indicators", pd.DataFrame())

In [17]:
economic= pd.merge(economic_activity, countries, on ="country_id", how="inner")
labour_market = pd.merge(labour_market_jobs, countries, on ="country_id", how="inner")
trade= pd.merge(trade_globalization, countries, on ="country_id", how="inner")
poverty= pd.merge(poverty_inequality, countries, on ="country_id", how="inner")
environment= pd.merge(environmental_indicators, countries, on ="country_id", how="inner")
health=pd.merge(health_indicators, countries, on ="country_id", how="inner")
technology=pd.merge(technology_indicators, countries, on ="country_id", how="inner")

In [18]:
economic.drop(columns=["indicator_id","name","id"], inplace=True)
trade.drop(columns=["indicator_id","name","id"], inplace=True)
labour_market.drop(columns=["indicator_id","name","id"], inplace=True)
poverty.drop(columns=["indicator_id","name","id"], inplace=True)
environment.drop(columns=["indicator_id","name","id"], inplace=True)
health.drop(columns=["indicator_id","name","id"], inplace=True)
technology.drop(columns=["indicator_id","name","id"], inplace=True)

In [19]:
economic

,country_id,country_name,indicator_name,year,value,region,incomeLevel,longitude,latitude
0,ZH,Africa Eastern and Southern,GDP growth (annual %),2025,3.743016,Aggregates,Aggregates,,
1,ZH,Africa Eastern and Southern,GDP growth (annual %),2024,2.787931,Aggregates,Aggregates,,
2,ZH,Africa Eastern and Southern,GDP growth (annual %),2023,1.941382,Aggregates,Aggregates,,
3,ZH,Africa Eastern and Southern,GDP growth (annual %),2022,3.668029,Aggregates,Aggregates,,
4,ZH,Africa Eastern and Southern,GDP growth (annual %),2021,4.452643,Aggregates,Aggregates,,
...,...,...,...,...,...,...,...,...,...
5295,ZW,Zimbabwe,GDP per capita (current US$),2020,2059.637040,Sub-Saharan Africa,Lower middle income,31.0672,-17.8312
5296,ZW,Zimbabwe,GDP per capita (current US$),2019,2184.521554,Sub-Saharan Africa,Lower middle income,31.0672,-17.8312
5297,ZW,Zimbabwe,GDP per capita (current US$),2018,2270.895319,Sub-Saharan Africa,Lower middle income,31.0672,-17.8312
5298,ZW,Zimbabwe,GDP per capita (current US$),2017,3445.449410,Sub-Saharan Africa,Lower middle income,31.0672,-17.8312
5299,ZW,Zimbabwe,GDP per capita (current US$),2016,1408.139453,Sub-Saharan Africa,Lower middle income,31.0672,-17.8312

In [20]:
economic.to_csv('economic.csv')
labour_market.to_csv('labour_market.csv')
trade.to_csv('trade.csv')
poverty.to_csv('poverty.csv')
environment.to_csv('environment.csv')
health.to_csv('health.csv')
technology.to_csv('technology.csv')

NameError: name 'technology' is not defined